<a href="https://colab.research.google.com/github/AnaghaTiwari/anaghatiwari/blob/gh-pages/webscraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# |exporti
import streamlit as st
import feedparser
from stramlit_jupyter import StreamlitPatcher, tqdm

In [35]:
!pip3 install streamlit>=1.36.0

In [46]:
# %%writefile app.py

st.subheader("A cached dataframe")

url = 'https://news.google.com/rss'
feed = feedparser.parse(url)

data = []

for entry in feed.entries:
    print(entry)
    data.append(entry)
df = pd.DataFrame(data)
df
# st.write(df)

### A cached dataframe

{'title': 'Trump Speech to Congress: Watch Live With Updates and Analysis - The New York Times', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': 'Trump Speech to Congress: Watch Live With Updates and Analysis - The New York Times'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://news.google.com/rss/articles/CBMickFVX3lxTFBsc0QxWmZTaVZ1amc1c0FmeXowNzJmZ0ItQkt0ZE9iRXdEMnlwd2hkX1g5S19WU1EwUnZZSlV2SUkwSmNlNzQ3ZHdJR2o0YlpRZFdnR0FRQUQxeFRjYjB5U0VOYTBPYXA4T2luT0s5Z2JSQQ?oc=5'}], 'link': 'https://news.google.com/rss/articles/CBMickFVX3lxTFBsc0QxWmZTaVZ1amc1c0FmeXowNzJmZ0ItQkt0ZE9iRXdEMnlwd2hkX1g5S19WU1EwUnZZSlV2SUkwSmNlNzQ3ZHdJR2o0YlpRZFdnR0FRQUQxeFRjYjB5U0VOYTBPYXA4T2luT0s5Z2JSQQ?oc=5', 'id': 'CBMickFVX3lxTFBsc0QxWmZTaVZ1amc1c0FmeXowNzJmZ0ItQkt0ZE9iRXdEMnlwd2hkX1g5S19WU1EwUnZZSlV2SUkwSmNlNzQ3ZHdJR2o0YlpRZFdnR0FRQUQxeFRjYjB5U0VOYTBPYXA4T2luT0s5Z2JSQQ', 'guidislink': False, 'published': 'Wed, 05 Mar 2025 03:07:00 GMT', 'published_parsed': time.struct_time(tm_year=2025, tm_mon=3, tm_mday=5, tm_hour=3, tm_min=7, tm_sec=0, tm_wday=2, tm_yday=64, tm_isdst=0), 'summary': '<ol><li><a href="https://news.google.com/rss/articles/CBMickFVX3lxTFBsc0QxWmZTaVZ1amc1c0FmeXowNzJmZ0ItQkt0ZE9iRXdEMnlwd2hkX1g5S19WU1EwUnZZSlV2SUkwSmNlNzQ3ZHdJR2o0YlpRZFdnR0FRQUQxeFRjYjB5U0VOYTBPYXA4T2luT0s5Z2JSQQ?oc=5" target="_blank">Trump Speech to Congress: Watch Live With Updates and Analysis</a>&nbsp;&nbsp;<font color="#6f6f6f">The New York Times</font></li><li><a href="https://news.google.com/rss/articles/CBMieEFVX3lxTE4xX1JNYkhYbVN4bW05ZldqMGtVQV9TcGJfOGFKNlVqRFpyRVBBRkZMX0UwVkxHdTQwVmRGVjZtWlRfLUVsYWVGc3RaMmFQeXdvTUl6elNaRFhYbWwySzJ3cGVHRWJGQl9LclhlLVlPVTEzUTdISVFSVA?oc=5" target="_blank">Who we\'ve spotted at Trump\'s address to Congress</a>&nbsp;&nbsp;<font color="#6f6f6f">Axios</font></li><li><a href="https://news.google.com/rss/articles/CBMioAFBVV95cUxOa2J5dmtPaXJ5cmZCVktkOWlqNlZVdGdtMkFoeVBXTGFxU2RFaUlGRDRwc1RvaVVxNE9QTWVqWXBCSUx1NlFmMnphZHZHemJONVd5cUtTSExMSExNWDJrcVdVRjlybVVVNEp2cDBwSXlGam13MW9GMHZFdmlzREtjRXp6UFJxMm0wRERUQ1haR1JlRjBsUERyd18wYWZGUVhD?oc=5" target="_blank">FACT FOCUS: A look at claims around Trump\'s initiatives as he prepares to address Congress</a>&nbsp;&nbsp;<font color="#6f6f6f">The Associated Press</font></li><li><a href="https://news.google.com/rss/articles/CBMiiwFBVV95cUxObUVRTGJZM0dDemZMdWZILTRVRHNMMTh3azVRLTRmd2luVTF6d1hXVE15OXRZU2xtcEI1NElIaHFVVmFxcWJGMEp4NkhrQWNPZVBwQ29ZVUpYaFZOWXdnci1NN3V6SVpkWGluZDBfZjZnOEZqalRDd1UtMnlxbEFHRzZYVzVBRGM4b0Q40gGQAUFVX3lxTE52aFYyel81NUg3ZkZkakUwUXR5SzV1NXVBVHYwd0pNbEZ3QjdkaXZSZzM3V2FnNm1BN01kZjRMVllYWkZfZnU1NjZ4S25qMDF2c3IxZkxqMlQzZ1RDRWVFN0g1TGg2Q3ZJYmtZcktqVVNNYXpWQnJ3ODRkRnpwXy1YeTN6bGdZbHl2bEZJTzFYNw?oc=5" target="_blank">Trump declares \'America is back\' in speech before Congress</a>&nbsp;&nbsp;<font color="#6f6f6f">Fox News</font></li></ol>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': '<ol><li><a href="https://news.google.com/rss/articles/CBMickFVX3lxTFBsc0QxWmZTaVZ1amc1c0FmeXowNzJmZ0ItQkt0ZE9iRXdEMnlwd2hkX1g5S19WU1EwUnZZSlV2SUkwSmNlNzQ3ZHdJR2o0YlpRZFdnR0FRQUQxeFRjYjB5U0VOYTBPYXA4T2luT0s5Z2JSQQ?oc=5" target="_blank">Trump Speech to Congress: Watch Live With Updates and Analysis</a>&nbsp;&nbsp;<font color="#6f6f6f">The New York Times</font></li><li><a href="https://news.google.com/rss/articles/CBMieEFVX3lxTE4xX1JNYkhYbVN4bW05ZldqMGtVQV9TcGJfOGFKNlVqRFpyRVBBRkZMX0UwVkxHdTQwVmRGVjZtWlRfLUVsYWVGc3RaMmFQeXdvTUl6elNaRFhYbWwySzJ3cGVHRWJGQl9LclhlLVlPVTEzUTdISVFSVA?oc=5" target="_blank">Who we\'ve spotted at Trump\'s address to Congress</a>&nbsp;&nbsp;<font color="#6f6f6f">Axios</font></li><li><a href="https://news.google.com/rss/articles/CBMioAFBVV95cUxOa2J5dmtPaXJ5cmZCVktkOWlqNlZVdGdtMkFoeVBXTGFxU2RFaUlGRDRwc1RvaVVxNE9QTWVqWXBCSUx1NlFmMnphZHZHemJONVd5cUtTSExMSExNWDJrcVdVRjlybVVVNEp2cDBwSXlGam13MW9GMHZFdmlzREtjRXp6UFJxMm0wRERUQ1haR1JlRjBsUERyd18wYWZGUVhD?oc=5" target="_blank">FACT FOCUS: A look at claims around Trump\'s initiatives as he prepares to address Congress</a>&nbsp;&nbsp;<font color="#6f6f6f">The Associated Press</font></li><li><a href="https://news.google.com/rss/articles/CBMiiwFBVV95cUxObUVRTGJZM0dDemZMdWZILTRVRHNMMTh3azVRLTRmd2luVTF6d1hXVE15OXRZU2xtcEI1NElIaHFVVmFxcWJGMEp4NkhrQWNPZVBwQ29ZVUpYaFZOWXdnci1NN3V6SVpkWGluZDBfZjZnOEZqalRDd1UtMnlxbEFHRzZYVzVBRGM4b0Q40gGQAUFVX3lxTE52aFYyel81NUg3ZkZkakUwUXR5SzV1NXVBVHYwd0pNbEZ3QjdkaXZSZzM3V2FnNm1BN01kZjRMVllYWkZfZnU1NjZ4S25qMDF2c3IxZkxqMlQzZ1RDRWVFN0g1TGg2Q3ZJYmtZcktqVVNNYXpWQnJ3ODRkRnpwXy1YeTN6bGdZbHl2bEZJTzFYNw?oc=5" target="_blank">Trump declares \'America is back\' in speech before Congress</a>&nbsp;&nbsp;<font color="#6f6f6f">Fox News</font></li></ol>'}, 'source': {'href': 'https://www.nytimes.com', 'title': 'The New York Times'}}
{'title': 'Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests - The Associated Press', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': 'Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests - The Associated Press'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5'}], 'link': 'https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5', 'id': 'CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0', 'guidislink': False, 'published': 'Tue, 04 Mar 2025 17:35:00 GMT', 'published_parsed': time.struct_time(tm_year=2025, tm_mon=3, tm_mday=4, tm_hour=17, tm_min=35, tm_sec=0, tm_wday=1, tm_yday=63, tm_isdst=0), 'summary': '<ol><li><a href="https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5" target="_blank">Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests</a>&nbsp;&nbsp;<font color="#6f6f6f">The Associated Press</font></li><li><a href="https://news.google.com/rss/articles/CBMinAFBVV95cUxPTHFlREZIaGRnX3ZIUnFBZFlLYzRSNW5EYjZULVZ6bWZsS3IwX2J5M2c4cDRRc1dOcGwtblg3ZmJlYkQ3RkJZeE9fbWlQUU8yOXB6SVpXbkQ3RUpBMlNCYk5FT1FhSWJqV0M1UHVxTVkyNnNXR05ENWxILVJucFJYeTdLQTdSc3lPVEp2dVdUUWNwd2dLNlZHX2tSVVc?oc=5" target="_blank">No more in-person town halls, NRCC chief tells House Republicans</a>&nbsp;&nbsp;<font color="#6f6f6f">POLITICO</font></li><li><a href="https://news.google.com/rss/articles/CBMipAFBVV95cUxQNlJCWlA0bXBZZExCUW84N3MtQllTZXgwZFZuOG52SUdCRGVRMUF6aXZVNUVWQzhDdHhuUTFUMjNJZFhmS19wSmV6RlVRakJRbUdXeG0zTGRDWThoeThFaVBTcV9HNVktWHh0bVdNVkpWSVFaSm5fTHNhT1QzU1VVS28tUm9XaHgycEZYOFpEN0dpb290U053S044ZEtXY0ZZS1ZYOQ?oc=5" target="_blank">US House speaker urges lawmakers to avoid town hall meetings</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMihwFBVV95cUxPYmgwYVhLdzhKUnE0d0U5ZFA5bDBFQW5kaFBxbHloNXZjTEE2UTNJN2plUUtpWXVQRUR0WURYdUd5NU82NldYSUVBTmx1elltT29hRjZDWVI0b0k4MWJ6azZxQmppdVVlckFLUmhxR1JCLWZ5MkFQOFNsV3psNEEtQVBLTjhkNUk?oc=5" target="_blank">After explosive town halls, Republicans rethink how to reach voters</a>&nbsp;&nbsp;<font color="#6f6f6f">The Washington Post</font></li></ol>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': '<ol><li><a href="https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5" target="_blank">Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests</a>&nbsp;&nbsp;<font color="#6f6f6f">The Associated Press</font></li><li><a href="https://news.google.com/rss/articles/CBMinAFBVV95cUxPTHFlREZIaGRnX3ZIUnFBZFlLYzRSNW5EYjZULVZ6bWZsS3IwX2J5M2c4cDRRc1dOcGwtblg3ZmJlYkQ3RkJZeE9fbWlQUU8yOXB6SVpXbkQ3RUpBMlNCYk5FT1FhSWJqV0M1UHVxTVkyNnNXR05ENWxILVJucFJYeTdLQTdSc3lPVEp2dVdUUWNwd2dLNlZHX2tSVVc?oc=5" target="_blank">No more in-person town halls, NRCC chief tells House Republicans</a>&nbsp;&nbsp;<font color="#6f6f6f">POLITICO</font></li><li><a href="https://news.google.com/rss/articles/CBMipAFBVV95cUxQNlJCWlA0bXBZZExCUW84N3MtQllTZXgwZFZuOG52SUdCRGVRMUF6aXZVNUVWQzhDdHhuUTFUMjNJZFhmS19wSmV6RlVRakJRbUdXeG0zTGRDWThoeThFaVBTcV9HNVktWHh0bVdNVkpWSVFaSm5fTHNhT1QzU1VVS28tUm9XaHgycEZYOFpEN0dpb290U053S044ZEtXY0ZZS1ZYOQ?oc=5" target="_blank">US House speaker urges lawmakers to avoid town hall meetings</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMihwFBVV95cUxPYmgwYVhLdzhKUnE0d0U5ZFA5bDBFQW5kaFBxbHloNXZjTEE2UTNJN2plUUtpWXVQRUR0WURYdUd5NU82NldYSUVBTmx1elltT29hRjZDWVI0b0k4MWJ6azZxQmppdVVlckFLUmhxR1JCLWZ5MkFQOFNsV3psNEEtQVBLTjhkNUk?oc=5" target="_blank">After explosive town halls, Republicans rethink how to reach voters</a>&nbsp;&nbsp;<font color="#6f6f6f">The Washington Post</font></li></ol>'}, 'source': {'href': 'https://apnews.com', 'title': 'The Associated Press'}}
{'title': 'Exclusive: US, Ukraine now plan to sign minerals deal, sources say - Reuters', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': 'Exclusive: US, Ukraine now plan to sign minerals deal, sources say - Reuters'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://news.google.com/rss/articles/CBMioAFBVV95cUxPblQzdkpxemRtRExnSkd6NC1GME9Nc3dZUDFfUmc1U3ZWY1ZkMGZicUtsUnJXbS1CNGk5Ml9vbktIaHV6elR2aTk2eFFzX1RIdUU3Yk9paVZTYzkwaHNPNFFQV1V1dHZ4WTJKeUx3a3M3S1ZHeC01aGNLUk1DTUZGVURsMG03UTFJWG1XVFRNWFlBZlBkX2ZXRFdKakpud2NQ?oc=5'}], 'link': 'https://news.google.com/rss/articles/CBMioAFBVV95cUxPblQzdkpxemRtRExnSkd6NC1GME9Nc3dZUDFfUmc1U3ZWY1ZkMGZicUtsUnJXbS1CNGk5Ml9vbktIaHV6elR2aTk2eFFzX1RIdUU3Yk9paVZTYzkwaHNPNFFQV1V1dHZ4WTJKeUx3a3M3S1ZHeC01aGNLUk1DTUZGVURsMG03UTFJWG1XVFRNWFlBZlBkX2ZXRFdKakpud2NQ?oc=5', 'id': 'CBMioAFBVV95cUxPblQzdkpxemRtRExnSkd6NC1GME9Nc3dZUDFfUmc1U3ZWY1ZkMGZicUtsUnJXbS1CNGk5Ml9vbktIaHV6elR2aTk2eFFzX1RIdUU3Yk9paVZTYzkwaHNPNFFQV1V1dHZ4WTJKeUx3a3M3S1ZHeC01aGNLUk1DTUZGVURsMG03UTFJWG1XVFRNWFlBZlBkX2ZXRFdKakpud2NQ', 'guidislink': False, 'published': 'Tue, 04 Mar 2025 21:37:57 GMT', 'published_parsed': time.struct_time(tm_year=2025, tm_mon=3, tm_mday=4, tm_hour=21, tm_min=37, tm_sec=57, tm_wday=1, tm_yday=63, tm_isdst=0), 'summary': '<ol><li><a href="https://news.google.com/rss/articles/CBMioAFBVV95cUxPblQzdkpxemRtRExnSkd6NC1GME9Nc3dZUDFfUmc1U3ZWY1ZkMGZicUtsUnJXbS1CNGk5Ml9vbktIaHV6elR2aTk2eFFzX1RIdUU3Yk9paVZTYzkwaHNPNFFQV1V1dHZ4WTJKeUx3a3M3S1ZHeC01aGNLUk1DTUZGVURsMG03UTFJWG1XVFRNWFlBZlBkX2ZXRFdKakpud2NQ?oc=5" target="_blank">Exclusive: US, Ukraine now plan to sign minerals deal, sources say</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMiswFBVV95cUxNcURGcDNQWWVMeXhzcWQ1eFVCbmh2LUNNdkU0Z3JLWUVQZldPZXdFNmdfN0xQSldJSG9aRDZxbWx3MU9oR25QdWlqbzFKNTlROFAwT1pqWTc2UUdXUW13bjJ4VUJWUHh6UVBGNnhoeWF3VDl6WGRoS0EzOGtwYkpfaUlxLTJKODM2aUNuV1lBM041NGdCUWZuYk1FVVB5UjFRMUhYMUZ2TU9kbEthS0FKeHltWQ?oc=5" target="_blank">Zelenskyy\'s visit with Trump to be a battle of wills in the Oval Office</a>&nbsp;&nbsp;<font color="#6f6f6f">USA TODAY</font></li><li><a href="https://news.google.com/rss/articles/CBMinwFBVV95cUxNZTBJR3d1X3BmaDlDdGRUcUhSRmpTRGY2NzB0MEpnQzFTYWwyamxrRXNIS0ptZDlhb0gtOXRYMWlZYXVyYzk5OVZmXzhuUW45QVNNcWNndW1TZG84X09rUlVfa09tMGotQW1kaFFkVjRjNGFla2lnNmJMc0FBVy1rejFOWEgzcjhoRzN6LTE1al9CYkhVYnNyTWhEVUU3WEXSAaQBQVVfeXFMUG53bG00NmZGZU5ROVBYN25iMDFVTHlBSC1CUUxvNkNzUUFMWXllenlrYzNtU1JLQ0FZd2tPRjhrcVE2OVpLOXRIdzJHMWZSalFhdlI4eDJ0RWZ2MGJYMVh6Uzg4U3FKVVJpMDZsclg3NEtkTTNoaXRrQ2ZhWlZ3ejNXM09KZVdWOUFnbHAtdU1nTXdwMzBmajkxcmt3V1JWcDBlS0s?oc=5" target="_blank">US, Ukraine sound optimistic notes on mineral deal</a>&nbsp;&nbsp;<font color="#6f6f6f">The Hill</font></li><li><a href="https://news.google.com/rss/articles/CBMitgFBVV95cUxOZFE1VV9admpienN6NWtweUczNmhGQ0hDS2RRcklBSVFHMlZ4c05vc1VQV3dWZWRCWTFJMFVVeHRMU21nQVZzcmYwbGl2QnUtaXlKWW1LWkgzaHV0MlEzeTlhUXdNakZva1RsYUF3LVloRUxYZGpzNHU4bWRVV2hBWHI2SDVodElJQ09FM0NDZnJQa3F5eXVPbXVvclgtQlE0UUM4bHRCVEdobjNSSmgteXZOUElVdw?oc=5" target="_blank">Trump Team Optimistic About Minerals Deal After Zelenskiy Pledge</a>&nbsp;&nbsp;<font color="#6f6f6f">Bloomberg</font></li><li><a href="https://news.google.com/rss/articles/CBMiqwFBVV95cUxNMmhWVmpnZXR6N1RrSGhnb1kyNHB0emhieVZzQXdNVFZDTkFQVDRWZ2JhZXlHT0VMX0dYTmNZNVNPV3JremRuRXU3YUxGOTlWMjNUTWdjV1RKVDRIaThlQWZkQnp4LTNyeGlGTm9EUV9OWkFyeXh6N2ZBT3JqTGF3Y0xsQ3laeWtuNGdvNy1Rb1U4MUgyVm9UajRBWHVTMzZmSkJBdURlRWJNZ0HSAbABQVVfeXFMT3lRcy1jQkVzd3RKT0dCM042UWxWdXFZTEZtQXEtNDNMRUFzWUNkbFFHbFdyd242QUx1TGxHT0ZJaWZNSXh1Tnd2NmxtWWtqLTY0aXlVNGdIckxQMXA1STYxTGRVUU9fMGdWMEdqUHAwb3NiaU92aXdFLXRGSnk1VnNEaGljd2owRTZiOWNRQWlUODNNeHJFcjdGd2pGY2Fhd2lSMFZ1c0czTjZSRlhFelg?oc=5" target="_blank">Ukraine’s Zelenskyy ‘ready’ for minerals deal after bust-up with Trump</a>&nbsp;&nbsp;<font color="#6f6f6f">Al Jazeera English</font></li></ol>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': '<ol><li><a href="https://news.google.com/rss/articles/CBMioAFBVV95cUxPblQzdkpxemRtRExnSkd6NC1GME9Nc3dZUDFfUmc1U3ZWY1ZkMGZicUtsUnJXbS1CNGk5Ml9vbktIaHV6elR2aTk2eFFzX1RIdUU3Yk9paVZTYzkwaHNPNFFQV1V1dHZ4WTJKeUx3a3M3S1ZHeC01aGNLUk1DTUZGVURsMG03UTFJWG1XVFRNWFlBZlBkX2ZXRFdKakpud2NQ?oc=5" target="_blank">Exclusive: US, Ukraine now plan to sign minerals deal, sources say</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMiswFBVV95cUxNcURGcDNQWWVMeXhzcWQ1eFVCbmh2LUNNdkU0Z3JLWUVQZldPZXdFNmdfN0xQSldJSG9aRDZxbWx3MU9oR25QdWlqbzFKNTlROFAwT1pqWTc2UUdXUW13bjJ4VUJWUHh6UVBGNnhoeWF3VDl6WGRoS0EzOGtwYkpfaUlxLTJKODM2aUNuV1lBM041NGdCUWZuYk1FVVB5UjFRMUhYMUZ2TU9kbEthS0FKeHltWQ?oc=5" target="_blank">Zelenskyy\'s visit with Trump to be a battle of wills in the Oval Office</a>&nbsp;&nbsp;<font color="#6f6f6f">USA TODAY</font></li><li><a href="https://news.google.com/rss/articles/CBMinwFBVV95cUxNZTBJR3d1X3BmaDlDdGRUcUhSRmpTRGY2NzB0MEpnQzFTYWwyamxrRXNIS0ptZDlhb0gtOXRYMWlZYXVyYzk5OVZmXzhuUW45QVNNcWNndW1TZG84X09rUlVfa09tMGotQW1kaFFkVjRjNGFla2lnNmJMc0FBVy1rejFOWEgzcjhoRzN6LTE1al9CYkhVYnNyTWhEVUU3WEXSAaQBQVVfeXFMUG53bG00NmZGZU5ROVBYN25iMDFVTHlBSC1CUUxvNkNzUUFMWXllenlrYzNtU1JLQ0FZd2tPRjhrcVE2OVpLOXRIdzJHMWZSalFhdlI4eDJ0RWZ2MGJYMVh6Uzg4U3FKVVJpMDZsclg3NEtkTTNoaXRrQ2ZhWlZ3ejNXM09KZVdWOUFnbHAtdU1nTXdwMzBmajkxcmt3V1JWcDBlS0s?oc=5" target="_blank">US, Ukraine sound optimistic notes on mineral deal</a>&nbsp;&nbsp;<font color="#6f6f6f">The Hill</font></li><li><a href="https://news.google.com/rss/articles/CBMitgFBVV95cUxOZFE1VV9admpienN6NWtweUczNmhGQ0hDS2RRcklBSVFHMlZ4c05vc1VQV3dWZWRCWTFJMFVVeHRMU21nQVZzcmYwbGl2QnUtaXlKWW1LWkgzaHV0MlEzeTlhUXdNakZva1RsYUF3LVloRUxYZGpzNHU4bWRVV2hBWHI2SDVodElJQ09FM0NDZnJQa3F5eXVPbXVvclgtQlE0UUM4bHRCVEdobjNSSmgteXZOUElVdw?oc=5" target="_blank">Trump Team Optimistic About Minerals Deal After Zelenskiy Pledge</a>&nbsp;&nbsp;<font color="#6f6f6f">Bloomberg</font></li><li><a href="https://news.google.com/rss/articles/CBMiqwFBVV95cUxNMmhWVmpnZXR6N1RrSGhnb1kyNHB0emhieVZzQXdNVFZDTkFQVDRWZ2JhZXlHT0VMX0dYTmNZNVNPV3JremRuRXU3YUxGOTlWMjNUTWdjV1RKVDRIaThlQWZkQnp4LTNyeGlGTm9EUV9OWkFyeXh6N2ZBT3JqTGF3Y0xsQ3laeWtuNGdvNy1Rb1U4MUgyVm9UajRBWHVTMzZmSkJBdURlRWJNZ0HSAbABQVVfeXFMT3lRcy1jQkVzd3RKT0dCM042UWxWdXFZTEZtQXEtNDNMRUFzWUNkbFFHbFdyd242QUx1TGxHT0ZJaWZNSXh1Tnd2NmxtWWtqLTY0aXlVNGdIckxQMXA1STYxTGRVUU9fMGdWMEdqUHAwb3NiaU92aXdFLXRGSnk1VnNEaGljd2owRTZiOWNRQWlUODNNeHJFcjdGd2pGY2Fhd2lSMFZ1c0czTjZSRlhFelg?oc=5" target="_blank">Ukraine’s Zelenskyy ‘ready’ for minerals deal after bust-up with Trump</a>&nbsp;&nbsp;<font color="#6f6f6f">Al Jazeera English</font></li></ol>'}, 'source': {'href': 'https://www.reuters.com', 'title': 'Reuters'}}

,title,title_detail,links,link,id,guidislink,published,published_parsed,summary,summary_detail,source
0,Trump Speech to Congress: Watch Live With Upda...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMickFVX...,CBMickFVX3lxTFBsc0QxWmZTaVZ1amc1c0FmeXowNzJmZ0...,False,"Wed, 05 Mar 2025 03:07:00 GMT","(2025, 3, 5, 3, 7, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
1,Speaker Johnson tells GOP lawmakers to skip to...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UX...,False,"Tue, 04 Mar 2025 17:35:00 GMT","(2025, 3, 4, 17, 35, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://apnews.com', 'title': 'The A..."
2,"Exclusive: US, Ukraine now plan to sign minera...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMioAFBV...,CBMioAFBVV95cUxPblQzdkpxemRtRExnSkd6NC1GME9Nc3...,False,"Tue, 04 Mar 2025 21:37:57 GMT","(2025, 3, 4, 21, 37, 57, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.reuters.com', 'title': '..."
3,Texas besieged by multiple fires as deadly sto...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMimwFBV...,CBMimwFBVV95cUxPRVBxY29yS2JlTE1pSEt2Q2RmU05TeX...,False,"Wed, 05 Mar 2025 01:38:00 GMT","(2025, 3, 5, 1, 38, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.cnn.com', 'title': 'CNN'}"
4,Trump administration prepares to sell off fede...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMijwFBV...,CBMijwFBVV95cUxNbm8xSFFCLWdqV0dKVjl5eGkyUlpXU0...,False,"Wed, 05 Mar 2025 01:21:00 GMT","(2025, 3, 5, 1, 21, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.cnn.com', 'title': 'CNN'}"
5,Arab leaders endorse Egyptian counterproposal ...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiogFBV...,CBMiogFBVV95cUxOVFA3Ni1kTHE2TDdjeG1nTjFSeDhQSF...,False,"Tue, 04 Mar 2025 19:27:00 GMT","(2025, 3, 4, 19, 27, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.pbs.org', 'title': 'PBS ..."
6,Democratic Rep. Al Green escorted out of chamb...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMicEFVX...,CBMicEFVX3lxTE9vU1gtbEp4cXhWdXluN0RjUnhCYUFMTD...,False,"Wed, 05 Mar 2025 02:39:48 GMT","(2025, 3, 5, 2, 39, 48, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.axios.com', 'title': 'Ax..."
7,Fired LAFD chief loses appeal of dismissal aft...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiugFBV...,CBMiugFBVV95cUxOdDVJR3FlbnMzQzZ3YUxhaXNndW5NMj...,False,"Mon, 03 Mar 2025 23:29:39 GMT","(2025, 3, 3, 23, 29, 39, 0, 62, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nbclosangeles.com', 'tit..."
8,"Lincoln Díaz-Balart, a ‘Free Cuba’ Republican ...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiggFBV...,CBMiggFBVV95cUxOMFlESGJYelVGVjQ4MkhoUzJCR0g3QU...,False,"Tue, 04 Mar 2025 22:53:33 GMT","(2025, 3, 4, 22, 53, 33, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
9,Zelenskyy suggests Ukraine didn't receive dire...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMixwFBV...,CBMixwFBVV95cUxOdk1KQ1FWM0FTemtNeHV4TkVzejQ4X1...,False,"Tue, 04 Mar 2025 21:00:11 GMT","(2025, 3, 4, 21, 0, 11, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.pbs.org', 'title': 'PBS ..."
10,JD Vance Ignites Outrage in UK With ‘Random Co...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMihAFBV...,CBMihAFBVV95cUxONG9WUFhfMXI1clkxc2dOOUhlZmRVRW...,False,"Tue, 04 Mar 2025 16:31:37 GMT","(2025, 3, 4, 16, 31, 37, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
11,Germany moves to rewrite debt rules to unleash...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiogFBV...,CBMiogFBVV95cUxOMzVoRHNpYV9LcW11YW1ranJqOHAxTk...,False,"Tue, 04 Mar 2025 19:54:00 GMT","(2025, 3, 4, 19, 54, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.politico.eu', 'title': '..."
12,America vs. The World: Trump Shows How Far He ...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMie0FVX...,CBMie0FVX3lxTFBucVRKZ19RWXhXdnY5QXJUZjRzaURmam...,False,"Tue, 04 Mar 2025 18:30:20 GMT","(2025, 3, 4, 18, 30, 20, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
13,Pope Francis in stable condition after episode...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxOVF9xZHRtZExuaXBTcTU3SFdIV1ZQeU...,False,"Tue, 04 Mar 2025 18:57:00 GMT","(2025, 3, 4, 18, 57, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://edition.cnn.com', 'title': '..."
14,BlackRock to take control of ports in Panama C...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMinwFBV...,CBMinwFBVV95cUxPR1pUNWtrNndUeF8xblFLRFdMalFLMF...,False,"Tue, 04 Mar 2025 19:47:00 GMT","(2025, 3, 4, 19, 47, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://nypost.com', 'title': 'New Y..."
15,China's parliament lines up stimulus to fend o...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMipgFBV...,CBMipgFBVV95cUxNMFVjUU9jdjFUaVJhLXJfdURqNHRaWm...,False,"Wed, 05 Mar 2025 02:39:00 GMT","(2025, 3, 5, 2, 39, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.reuters.com', 'title': '..."
16,Automakers tap COVID playbook to cope with Tru...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiYEFVX...,CBMiYEFVX3lxTE1VeXU1V284RWlQdTJMcS1maVF4NkxCLU...,False,"Tue, 04 Mar 2025 23:39:10 GMT","(2025, 3, 4, 23, 39, 10, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.axios.com', 'title': 'Ax..."
17,"Stock Market News, March 4, 2025: : Dow ends d...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiwAFBV...,CBMiwAFBVV95cUxObXlScGw2WUZYc29mWEhHNk1lQTE5bm...,False,"Tue, 04 Mar 2025 20:39:00 GMT","(2025, 3, 4, 20, 39, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.marketwatch.com', 'title..."
18,Apple unveils upgraded iPad Air ahead of expec...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMirgFBV...,CBMirgFBVV95cUxOWDRyaDRPZHFIeE9mOU5HM3R6X3FKej...,False,"Tue, 04 Mar 2025 20:33:00 GMT","(2025, 3, 4, 20, 33, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://nypost.com', 'title': 'New Y..."
19,Google’s Latest Pixel Feature Drop Will Let Pi...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMisgFBV...,CBMisgFBVV95cUxPZGFZY3QzWmtueFVaT2hXMENobnl6ST...,False,"Tue, 04 Mar 2025 17:01:05 GMT","(2025, 3, 4, 17, 1, 5, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://gizmodo.com', 'title': 'Gizm..."
20,Nvidia’s GeForce RTX 5070 Founders Edition car...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxPMWRIUWhOSGR0a3pERlo2b1ZjU01NYW...,False,"Tue, 04 Mar 2025 22:51:17 GMT","(2025, 3, 4, 22, 51, 17, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.theverge.com', 'title': ..."
21,uBlock Origin lives on despite Chrome automati...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiiwFBV...,CBMiiwFBVV95cUxOYVh5VXJvVjJqdWhQRVdNREZrdmVLeH...,False,"Tue, 04 Mar 2025 19:49:00 GMT","(2025, 3, 4, 19, 49, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.androidpolice.com', 'tit..."
22,Fox News Entertainment Newsletter: Gene Hackma...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMixAFBV...,CBMixAFBVV95cUxOcFh2UnFTckU3ZVhMSGxKZmg5akQyMX...,False,"Tue, 04 Mar 2025 18:48:58 GMT","(2025, 3, 4, 18, 48, 58, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.foxnews.com', 'title': '..."
23,Demi Moore Celebrates Mikey Madison’s Oscar Wi...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiqwFBV...,CBMiqwFBVV95cUxPbklnRWhmS3BkYW9Da1JKejA5NjY5T0...,False,"Tue, 04 Mar 2025 14:21:00 GMT","(2025, 3, 4, 14, 21, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://variety.com', 'title': 'Vari..."
24,Meghan Markle Corrects Mindy Kaling On Proper ...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMijwFBV...,CBMijwFBVV95cUxOZDR6bjZYOENtQXhTVUdheFlFRjRucz...,False,"Tue, 04 Mar 2025 20:45:36 GMT","(2025, 3, 4, 20, 45, 36, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.yahoo.com', 'title': 'Ya..."
25,Ben Affleck affectionately holds ex-wife Jenni...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMijwFBV...,CBMijwFBVV95cUxQMFY4U3JxLUYwbENSZU1ZRUR4Z25jaE...,False,"Tue, 04 Mar 2025 22:45:00 GMT","(2025, 3, 4, 22, 45, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.yahoo.com', 'title': 'Ya..."
26,"With Kyrie Irving out and Luka Dončić in L.A.,...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMitgFBV...,CBMitgFBVV95cUxPbUNpNUNhS0tmdHVJYWpsb0lTUEpqaX...,False,"Tue, 04 Mar 2025 22:52:30 GMT","(2025, 3, 4, 22, 52, 30, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
27,Davante Adams Released by Jets amid Aaron Rodg...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiswFBV...,CBMiswFBVV95cUxQRXo4SENFb3h3UE9wQXFuWDg2X1MxSV...,False,"Tue, 04 Mar 2025 21:45:00 GMT","(2025, 3, 4, 21, 45, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://bleacherreport.com', 'title'..."
28,New rumors of Shedeur Sanders’ ‘unprofessional...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiqgFBV...,CBMiqgFBVV95cUxQQzBadUl3WHJsSzhKN3c4MGRJUmpxRH...,False,"Tue, 04 Mar 2025 21:26:00 GMT","(2025, 3, 4, 21, 26, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://nypost.com', 'title': 'New Y..."
29,Wide Receivers in Free Agency | Who’s Out Ther...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxNTzJzem9iSlhCQ1VaWXVFam03SzVveF...,False,"Tue, 04 Mar 2025 18:12:46 GMT","(2025, 3, 4, 18, 12, 46, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.baltimoreravens.com', 't..."
30,“Wooly mice” a test run for mammoth gene editi...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMikAFBV...,CBMikAFBVV95cUxOVnk4R2w3ZUEzd01nbER6dUw3Sk5LcW...,False,"Tue, 04 Mar 2025 23:03:45 GMT","(2025, 3, 4, 23, 3, 45, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://arstechnica.com', 'title': '..."
31,NASA's two stuck astronauts are finally closin...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMisAFBV...,CBMisAFBVV95cUxOemZQOVZTaG9KX3ZNTE44V210MXpfNn...,False,"Tue, 04 Mar 2025 18:45:55 GMT","(2025, 3, 4, 18, 45, 55, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://abcnews.go.com', 'title': 'A..."
32,SpaceX loses a Falcon 9 booster and scrubs a S...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMibkFVX...,CBMibkFVX3lxTE1KTllSTmlnSERKU2NlNEFLMDNOeGNkVE...,False,"Tue, 04 Mar 2025 15:31:00 GMT","(2025, 3, 4, 15, 31, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.theregister.com', 'title..."
33,"The Sun's Activity Can Trigger Earthquakes, An...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxPbExSSS0xZlA0eTdKUlFQMEc2a3A0ek...,False,"Tue, 04 Mar 2025 16:02:20 GMT","(2025, 3, 4, 16, 2, 20, 1, 63, 0)","<a href=""https://news.google.com/rss/articles/...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.sciencealert.com', 'titl..."
34,RFK Jr.’s focus on vitamin A for measles worri...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMijgFBV...,CBMijgFBVV95cUxOaGlEUWRwLXZYbVRqUGVjWEdLdEVCNX...,False,"Wed, 05 Mar 2025 02:44:47 GMT","(2025, 3, 5, 2, 44, 47, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.washingtonpost.com', 'ti..."
35,Multnomah County reports increase in Shigella-...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiywFBV...,CBMiywFBVV95cUxOY1FibDE4T0NLaE14M09BM2Q5UWtsLU...,False,"Tue, 04 Mar 2025 00:35:00 GMT","(2025, 3, 4, 0, 35, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.kgw.com', 'title': 'KGW...."
36,Why Sleep Gets Harder With Age - Newsmax,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMikwFBV...,CBMikwFBVV95cUxQa3J1OTl4cXZoQUNiSVFPYjAyTDBLR2...,False,"Tue, 04 Mar 2025 19:18:15 GMT","(2025, 3, 4, 19, 18, 15, 1, 63, 0)","<a href=""https://news.google.com/rss/articles/...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.newsmax.com', 'title': '..."
37,Presidential Message on Colorectal Cancer Awar...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiuwFBV...,CBMiuwFBVV95cUxQak5icHd5cV9Ia0FmSFVsQ3h3M1lKT0...,False,"Tue, 04 Mar 2025 14:43:19 GMT","(2025, 3, 4, 14, 43, 19, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.whitehouse.gov', 'title'..."

In [60]:
import ipywidgets as widgets
from IPython.display import display, HTML
import threading
import time
import feedparser

# Styling
style = """
    <style>
        .widget-button { background-color: #007BFF; color: white; font-size: 16px; }
        .widget-text { width: 400px; font-size: 14px; }
        .progress-bar { height: 10px; background-color: #007BFF; transition: width 0.5s; }
        .progress-container { width: 100%; background-color: #e0e0e0; height: 10px; }
        .output-box { border: 1px solid #ddd; padding: 10px; margin-top: 10px; background: #f9f9f9; }
    </style>
"""
display(HTML(style))

# Widgets
url_input = widgets.Text(placeholder="Enter RSS Link to Scrape", layout=widgets.Layout(width='400px'))
scrape_button = widgets.Button(description="Start Scraping", button_style='primary')
progress = widgets.IntProgress(value=0, min=0, max=100, step=20, bar_style='info')
output_area = widgets.Output()


def scrape_website(url):

    with output_area:
        output_area.clear_output()
        display(HTML(f'<p style="color:black; font-size:16=8px;font_family:Fort">Scraping started for: {url}</p>'))

    feed = feedparser.parse(url)

    feed = feedparser.parse(url)

    data = []

    for entry in feed.entries:
        print(entry)
        data.append(entry)
    df = pd.DataFrame(data)

    # with output_area:
    #     display(HTML(f'<div class="output-box"><strong>{entry.title}</strong><br><a href="{entry.link}" target="_blank">{entry.link}</a></div>'))
    # with output_area:
    #         display(HTML(f"<h3>Scraped Data:</h3>"))
    #         display(df)

    # with output_area:
    #     display(HTML(f'<p style="color:green; font-size:16px;">Scraping complete for: {url}</p>'))
    return df


def start_scraping(_):
    progress.value = 0
    output_area.clear_output()

    # Start the scraping in a separate thread
    def run_scraping():
        df = scrape_website(url_input.value)
        with output_area:
            display(HTML(f"<h3>Scraped Data:</h3>"))
            display(df)

    thread = threading.Thread(target=run_scraping())
    thread.start()

scrape_button.on_click(start_scraping)

# Display UI
display(widgets.VBox([url_input, scrape_button, progress, output_area]))

VBox(children=(Text(value='', layout=Layout(width='400px'), placeholder='Enter RSS Link to Scrape', style=Desc…

In [54]:
scrape_website('https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en')

{'title': 'Watch: Congressman Al Green ejected from chamber after disrupting Trump speech - BBC.com', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': 'Watch: Congressman Al Green ejected from chamber after disrupting Trump speech - BBC.com'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://news.google.com/rss/articles/CBMiV0FVX3lxTE5OTUVKN0VsZkF5bVJCVnN3bjlxRjlvX3JqUlpFUTBKcEF6NFQxOXFVVEpmc1RfMXdMdXBraWhfd1BueXE5SWRRWGlnOEcwb1J4X2YtVElXOA?oc=5'}], 'link': 'https://news.google.com/rss/articles/CBMiV0FVX3lxTE5OTUVKN0VsZkF5bVJCVnN3bjlxRjlvX3JqUlpFUTBKcEF6NFQxOXFVVEpmc1RfMXdMdXBraWhfd1BueXE5SWRRWGlnOEcwb1J4X2YtVElXOA?oc=5', 'id': 'CBMiV0FVX3lxTE5OTUVKN0VsZkF5bVJCVnN3bjlxRjlvX3JqUlpFUTBKcEF6NFQxOXFVVEpmc1RfMXdMdXBraWhfd1BueXE5SWRRWGlnOEcwb1J4X2YtVElXOA', 'guidislink': False, 'published': 'Wed, 05 Mar 2025 02:44:52 GMT', 'published_parsed': time.struct_time(tm_year=2025, tm_mon=3, tm_mday=5, tm_hour=2, tm_min=44, tm_sec=52, tm_wday=2, tm_yday=64, tm_isdst=0), 'summary': '<ol><li><a href="https://news.google.com/rss/articles/CBMiV0FVX3lxTE5OTUVKN0VsZkF5bVJCVnN3bjlxRjlvX3JqUlpFUTBKcEF6NFQxOXFVVEpmc1RfMXdMdXBraWhfd1BueXE5SWRRWGlnOEcwb1J4X2YtVElXOA?oc=5" target="_blank">Watch: Congressman Al Green ejected from chamber after disrupting Trump speech</a>&nbsp;&nbsp;<font color="#6f6f6f">BBC.com</font></li><li><a href="https://news.google.com/rss/articles/CBMihwFBVV95cUxNNFVMeXBZZlh0eG44YmVmV3RJbVpGakh1R19McFN2UnJVbmRIYnBkVTYwUW5FeGFrRDNmbk9sSUw2Sk5IT2RmeW9kZzZkaTM4a3VmcVhIYlo2cTkySUhZM2Fyd3g2Z01HMkt0TVc3d2YzbFBGRVpnb3QwLXlIZjNXTmpkSHdSV2fSAX5BVV95cUxOVkVTNUNmNHI3cTIzbjU5YWstUVJ0TGNGNEZxNjJSVmU1eF82MzhvSzZkMjJMVE14NWREdFJVY3FleGJmN1JTZDYwVjN4WVdQRTVDZWxfSkhkWWVQY2N4VEVQX0tGV2hMV1pwNUxYaHRPQlptUnktOUY4emktZ2c?oc=5" target="_blank">Rep. Al Green removed from House chamber as some Democrats ignore party guidance and seize Trump protest moments</a>&nbsp;&nbsp;<font color="#6f6f6f">CNN</font></li><li><a href="https://news.google.com/rss/articles/CBMitwFBVV95cUxPc19uTVIweVBXN0o1M2RZQ1NSQ1hwTHNQUXdzNWhaQ3pzQ2NEbXJ4X194ekxMbkdWWTR2VmxxZDFKMjhjUmtSOGdBOU9xR2hoeFNIRUZQZENHNWIwTERvejNkeFBSOUFQS05uNTF6cW5MckU3TkdlTGt0RHhNVTYtSEp5YU16cVhHczZ3RDkzemxKeWVpLW9LdDJpZWR1emdYMkRrTHlzNXpTbWgzSi02STJSLVNjUmc?oc=5" target="_blank">Live updates: Trump’s joint address to Congress interrupted by Democrats</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMihgFBVV95cUxPaGt3M1diTGY1QXFoNWg0elRiMW5oYnNLemFrSmo5NmdFT1YydjQ4b2dyYVMxNGg3VF8td2luY3YxTm53Rng0eXZINnd3OG11VTVDRlJTUXF6VExtQlQ0ZzZsaHJ1eXlGaHNJYTdiMnRPSzNuWW5welhDOW9OQTVkNFBidU43dw?oc=5" target="_blank">Trump speech to Congress repeatedly rocked by chaotic Democratic disruptions</a>&nbsp;&nbsp;<font color="#6f6f6f">Axios</font></li></ol>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': '<ol><li><a href="https://news.google.com/rss/articles/CBMiV0FVX3lxTE5OTUVKN0VsZkF5bVJCVnN3bjlxRjlvX3JqUlpFUTBKcEF6NFQxOXFVVEpmc1RfMXdMdXBraWhfd1BueXE5SWRRWGlnOEcwb1J4X2YtVElXOA?oc=5" target="_blank">Watch: Congressman Al Green ejected from chamber after disrupting Trump speech</a>&nbsp;&nbsp;<font color="#6f6f6f">BBC.com</font></li><li><a href="https://news.google.com/rss/articles/CBMihwFBVV95cUxNNFVMeXBZZlh0eG44YmVmV3RJbVpGakh1R19McFN2UnJVbmRIYnBkVTYwUW5FeGFrRDNmbk9sSUw2Sk5IT2RmeW9kZzZkaTM4a3VmcVhIYlo2cTkySUhZM2Fyd3g2Z01HMkt0TVc3d2YzbFBGRVpnb3QwLXlIZjNXTmpkSHdSV2fSAX5BVV95cUxOVkVTNUNmNHI3cTIzbjU5YWstUVJ0TGNGNEZxNjJSVmU1eF82MzhvSzZkMjJMVE14NWREdFJVY3FleGJmN1JTZDYwVjN4WVdQRTVDZWxfSkhkWWVQY2N4VEVQX0tGV2hMV1pwNUxYaHRPQlptUnktOUY4emktZ2c?oc=5" target="_blank">Rep. Al Green removed from House chamber as some Democrats ignore party guidance and seize Trump protest moments</a>&nbsp;&nbsp;<font color="#6f6f6f">CNN</font></li><li><a href="https://news.google.com/rss/articles/CBMitwFBVV95cUxPc19uTVIweVBXN0o1M2RZQ1NSQ1hwTHNQUXdzNWhaQ3pzQ2NEbXJ4X194ekxMbkdWWTR2VmxxZDFKMjhjUmtSOGdBOU9xR2hoeFNIRUZQZENHNWIwTERvejNkeFBSOUFQS05uNTF6cW5MckU3TkdlTGt0RHhNVTYtSEp5YU16cVhHczZ3RDkzemxKeWVpLW9LdDJpZWR1emdYMkRrTHlzNXpTbWgzSi02STJSLVNjUmc?oc=5" target="_blank">Live updates: Trump’s joint address to Congress interrupted by Democrats</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMihgFBVV95cUxPaGt3M1diTGY1QXFoNWg0elRiMW5oYnNLemFrSmo5NmdFT1YydjQ4b2dyYVMxNGg3VF8td2luY3YxTm53Rng0eXZINnd3OG11VTVDRlJTUXF6VExtQlQ0ZzZsaHJ1eXlGaHNJYTdiMnRPSzNuWW5welhDOW9OQTVkNFBidU43dw?oc=5" target="_blank">Trump speech to Congress repeatedly rocked by chaotic Democratic disruptions</a>&nbsp;&nbsp;<font color="#6f6f6f">Axios</font></li></ol>'}, 'source': {'href': 'https://www.bbc.com', 'title': 'BBC.com'}}
{'title': 'Trump’s Latest Tariffs on Canada, Mexico and China Could Be His Biggest Gamble - The New York Times', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': 'Trump’s Latest Tariffs on Canada, Mexico and China Could Be His Biggest Gamble - The New York Times'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://news.google.com/rss/articles/CBMigAFBVV95cUxNY2pOenhzX25QQlZNUEZSc0tkVXVITWhrSTQzSHdSeVUxTFh1NFVuOGtNVVZHOE0tZnBnY0lWSkpOYjdlbFJMaEd2cjRBRFptMVlXUG1FM1N2Rkp1dVJOVTJ3dUo3ZDVvYXVVeUNCNnFYdWpPNHJZUjNaQ3Ffa1l3Mg?oc=5'}], 'link': 'https://news.google.com/rss/articles/CBMigAFBVV95cUxNY2pOenhzX25QQlZNUEZSc0tkVXVITWhrSTQzSHdSeVUxTFh1NFVuOGtNVVZHOE0tZnBnY0lWSkpOYjdlbFJMaEd2cjRBRFptMVlXUG1FM1N2Rkp1dVJOVTJ3dUo3ZDVvYXVVeUNCNnFYdWpPNHJZUjNaQ3Ffa1l3Mg?oc=5', 'id': 'CBMigAFBVV95cUxNY2pOenhzX25QQlZNUEZSc0tkVXVITWhrSTQzSHdSeVUxTFh1NFVuOGtNVVZHOE0tZnBnY0lWSkpOYjdlbFJMaEd2cjRBRFptMVlXUG1FM1N2Rkp1dVJOVTJ3dUo3ZDVvYXVVeUNCNnFYdWpPNHJZUjNaQ3Ffa1l3Mg', 'guidislink': False, 'published': 'Wed, 05 Mar 2025 01:30:23 GMT', 'published_parsed': time.struct_time(tm_year=2025, tm_mon=3, tm_mday=5, tm_hour=1, tm_min=30, tm_sec=23, tm_wday=2, tm_yday=64, tm_isdst=0), 'summary': '<ol><li><a href="https://news.google.com/rss/articles/CBMigAFBVV95cUxNY2pOenhzX25QQlZNUEZSc0tkVXVITWhrSTQzSHdSeVUxTFh1NFVuOGtNVVZHOE0tZnBnY0lWSkpOYjdlbFJMaEd2cjRBRFptMVlXUG1FM1N2Rkp1dVJOVTJ3dUo3ZDVvYXVVeUNCNnFYdWpPNHJZUjNaQ3Ffa1l3Mg?oc=5" target="_blank">Trump’s Latest Tariffs on Canada, Mexico and China Could Be His Biggest Gamble</a>&nbsp;&nbsp;<font color="#6f6f6f">The New York Times</font></li><li><a href="https://news.google.com/rss/articles/CBMilgFBVV95cUxPVlhMa083Ty1tSEd5eDhKenlQblBKVVhhV3lqQm1sYXZmQkg1NVZXMHJmS3NoWGFzSElXc1owdktsUDdQVDVmTDB4anhMV1Q4UXZVbTdpM04tZGY1cnJIaEFPNXAzcjBpaURKeS02VlB3NHozUVVraC1ZVThvU1FJbWVyOTNib0EtVUFJaHhidVd3aGxuRXfSAZsBQVVfeXFMUDU4S2Y4dXk2Wm1IbzJKbW1iRk1Cam5MeWhucktyTzktZlhHYmEzN1J2NXM2T2pibjBQdTJlV1BheDhkZXZGX01kbmlmVjh4ZWFRV0RLRjNaY1JQX0NUQnJIYWR3RXNsQTgxcHNlRnpHeVJSRVY3LUZTZjZqUThhX0hqdDJxWlAxZm9LcC1rMXMxOWtDR01JTFFZNUE?oc=5" target="_blank">Trump could scale back Canada, Mexico tariffs Wednesday, Lutnick says</a>&nbsp;&nbsp;<font color="#6f6f6f">CNBC</font></li><li><a href="https://news.google.com/rss/articles/CBMif0FVX3lxTFBzM05XUy1VZWVaWlV0YWlzNTJCLXE2OEVWWHN1VkhBMG4xV1hpYm9mSUVLdU8xdnNkVW5oeS1uMUpJS2ctNHNGZ3QwejdYdmplU3hoRGNobVl4YVdkOXNFZjhtTW1Na0NOeGtrMDZjZW4xTzZRbno5ZUpRMi1kM2fSAUdBVV95cUxOOERDUGdsYUdZb1dVTDBtSEgyZVBpNzZJSW1MQ2pPZHpRejNPWFBLeXc4eXNvS1JrNDlETWpXaHQ5LVJJS1ctcw?oc=5" target="_blank">One day into tariff war, U.S. says de-escalation now possible</a>&nbsp;&nbsp;<font color="#6f6f6f">CBC.ca</font></li><li><a href="https://news.google.com/rss/articles/CBMikgFBVV95cUxQZEpmWWw5aXhRUDBpX3pkWTkzRzU1bGd6blZEUm5vWFNCRTZ1d2NpdjdzcGpzVmRvSFp0Zmdwb2p2bTJsLVZkWGt5UWRjbUZoUHZ6S1YyWU9fYjJkQWJHN3FSZkotTFgtZnIwRzZxX2hxNDhCUWMtaHZTeHJfd09kRENDT1ZfUkN4d2pQa2pUc3BWZw?oc=5" target="_blank">Canada and China Retaliate Against Trump’s Tariffs, Amid Fears of Trade War</a>&nbsp;&nbsp;<font color="#6f6f6f">The New York Times</font></li><li><a href="https://news.google.com/rss/articles/CBMivwFBVV95cUxNdTNQTUtLSXpnNmF3bGlKUEs4LW1iQXNBQ2VvV0hvSnpfSWhHbVl6NVpON3RNNURnd0VVMFRLc0VYaGl6djdTSC02bVkzRFJ4S2xpNHZyYXdYY0psMHNvVDlSal9LUER6cGtwUTZOaGRQRDRMU1Vzc1diM25jT2FNTFZKTGFMM2NEMU9UdTFZRllRRXpWMW5sdmVLeHd3QU9rWHRLM3BxTkJVTGdSZUdjc2FBQ1J1YnRUX2lfcm1wSdIBxAFBVV95cUxNenhkRDZZelcyYTB2c2F6RF9nZ1JNMFFLQmxfSXI3bzIydEFKb1RYWlpKb2toeXJJTjgxeVJTRHFOOTIyTWp5XzNaOUlfbEpScmwyZC05azlHV29lTW1ZWFJ4WkpHcnlyb2oxa2dxM0tSMkJ3Um12Nm5rUzFBVnFCY1A1OWJ1UGdfZ1Q5aGpENW1ydzBpTk11alBnM3Z4SDV1eEFWZlpZZkhGZnhfakpaUXRSVUdXZ3dQWmRNdGFnWHFCM1g5?oc=5" target="_blank">Business owners, economists discuss potential impact of Trump\'s tariffs on Coloradans</a>&nbsp;&nbsp;<font color="#6f6f6f">CBS News</font></li></ol>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': '<ol><li><a href="https://news.google.com/rss/articles/CBMigAFBVV95cUxNY2pOenhzX25QQlZNUEZSc0tkVXVITWhrSTQzSHdSeVUxTFh1NFVuOGtNVVZHOE0tZnBnY0lWSkpOYjdlbFJMaEd2cjRBRFptMVlXUG1FM1N2Rkp1dVJOVTJ3dUo3ZDVvYXVVeUNCNnFYdWpPNHJZUjNaQ3Ffa1l3Mg?oc=5" target="_blank">Trump’s Latest Tariffs on Canada, Mexico and China Could Be His Biggest Gamble</a>&nbsp;&nbsp;<font color="#6f6f6f">The New York Times</font></li><li><a href="https://news.google.com/rss/articles/CBMilgFBVV95cUxPVlhMa083Ty1tSEd5eDhKenlQblBKVVhhV3lqQm1sYXZmQkg1NVZXMHJmS3NoWGFzSElXc1owdktsUDdQVDVmTDB4anhMV1Q4UXZVbTdpM04tZGY1cnJIaEFPNXAzcjBpaURKeS02VlB3NHozUVVraC1ZVThvU1FJbWVyOTNib0EtVUFJaHhidVd3aGxuRXfSAZsBQVVfeXFMUDU4S2Y4dXk2Wm1IbzJKbW1iRk1Cam5MeWhucktyTzktZlhHYmEzN1J2NXM2T2pibjBQdTJlV1BheDhkZXZGX01kbmlmVjh4ZWFRV0RLRjNaY1JQX0NUQnJIYWR3RXNsQTgxcHNlRnpHeVJSRVY3LUZTZjZqUThhX0hqdDJxWlAxZm9LcC1rMXMxOWtDR01JTFFZNUE?oc=5" target="_blank">Trump could scale back Canada, Mexico tariffs Wednesday, Lutnick says</a>&nbsp;&nbsp;<font color="#6f6f6f">CNBC</font></li><li><a href="https://news.google.com/rss/articles/CBMif0FVX3lxTFBzM05XUy1VZWVaWlV0YWlzNTJCLXE2OEVWWHN1VkhBMG4xV1hpYm9mSUVLdU8xdnNkVW5oeS1uMUpJS2ctNHNGZ3QwejdYdmplU3hoRGNobVl4YVdkOXNFZjhtTW1Na0NOeGtrMDZjZW4xTzZRbno5ZUpRMi1kM2fSAUdBVV95cUxOOERDUGdsYUdZb1dVTDBtSEgyZVBpNzZJSW1MQ2pPZHpRejNPWFBLeXc4eXNvS1JrNDlETWpXaHQ5LVJJS1ctcw?oc=5" target="_blank">One day into tariff war, U.S. says de-escalation now possible</a>&nbsp;&nbsp;<font color="#6f6f6f">CBC.ca</font></li><li><a href="https://news.google.com/rss/articles/CBMikgFBVV95cUxQZEpmWWw5aXhRUDBpX3pkWTkzRzU1bGd6blZEUm5vWFNCRTZ1d2NpdjdzcGpzVmRvSFp0Zmdwb2p2bTJsLVZkWGt5UWRjbUZoUHZ6S1YyWU9fYjJkQWJHN3FSZkotTFgtZnIwRzZxX2hxNDhCUWMtaHZTeHJfd09kRENDT1ZfUkN4d2pQa2pUc3BWZw?oc=5" target="_blank">Canada and China Retaliate Against Trump’s Tariffs, Amid Fears of Trade War</a>&nbsp;&nbsp;<font color="#6f6f6f">The New York Times</font></li><li><a href="https://news.google.com/rss/articles/CBMivwFBVV95cUxNdTNQTUtLSXpnNmF3bGlKUEs4LW1iQXNBQ2VvV0hvSnpfSWhHbVl6NVpON3RNNURnd0VVMFRLc0VYaGl6djdTSC02bVkzRFJ4S2xpNHZyYXdYY0psMHNvVDlSal9LUER6cGtwUTZOaGRQRDRMU1Vzc1diM25jT2FNTFZKTGFMM2NEMU9UdTFZRllRRXpWMW5sdmVLeHd3QU9rWHRLM3BxTkJVTGdSZUdjc2FBQ1J1YnRUX2lfcm1wSdIBxAFBVV95cUxNenhkRDZZelcyYTB2c2F6RF9nZ1JNMFFLQmxfSXI3bzIydEFKb1RYWlpKb2toeXJJTjgxeVJTRHFOOTIyTWp5XzNaOUlfbEpScmwyZC05azlHV29lTW1ZWFJ4WkpHcnlyb2oxa2dxM0tSMkJ3Um12Nm5rUzFBVnFCY1A1OWJ1UGdfZ1Q5aGpENW1ydzBpTk11alBnM3Z4SDV1eEFWZlpZZkhGZnhfakpaUXRSVUdXZ3dQWmRNdGFnWHFCM1g5?oc=5" target="_blank">Business owners, economists discuss potential impact of Trump\'s tariffs on Coloradans</a>&nbsp;&nbsp;<font color="#6f6f6f">CBS News</font></li></ol>'}, 'source': {'href': 'https://www.nytimes.com', 'title': 'The New York Times'}}
{'title': 'Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests - The Associated Press', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': 'Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests - The Associated Press'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5'}], 'link': 'https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5', 'id': 'CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0', 'guidislink': False, 'published': 'Tue, 04 Mar 2025 17:35:00 GMT', 'published_parsed': time.struct_time(tm_year=2025, tm_mon=3, tm_mday=4, tm_hour=17, tm_min=35, tm_sec=0, tm_wday=1, tm_yday=63, tm_isdst=0), 'summary': '<ol><li><a href="https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5" target="_blank">Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests</a>&nbsp;&nbsp;<font color="#6f6f6f">The Associated Press</font></li><li><a href="https://news.google.com/rss/articles/CBMihwFBVV95cUxPYmgwYVhLdzhKUnE0d0U5ZFA5bDBFQW5kaFBxbHloNXZjTEE2UTNJN2plUUtpWXVQRUR0WURYdUd5NU82NldYSUVBTmx1elltT29hRjZDWVI0b0k4MWJ6azZxQmppdVVlckFLUmhxR1JCLWZ5MkFQOFNsV3psNEEtQVBLTjhkNUk?oc=5" target="_blank">After explosive town halls, Republicans rethink how to reach voters</a>&nbsp;&nbsp;<font color="#6f6f6f">The Washington Post</font></li><li><a href="https://news.google.com/rss/articles/CBMipAFBVV95cUxQNlJCWlA0bXBZZExCUW84N3MtQllTZXgwZFZuOG52SUdCRGVRMUF6aXZVNUVWQzhDdHhuUTFUMjNJZFhmS19wSmV6RlVRakJRbUdXeG0zTGRDWThoeThFaVBTcV9HNVktWHh0bVdNVkpWSVFaSm5fTHNhT1QzU1VVS28tUm9XaHgycEZYOFpEN0dpb290U053S044ZEtXY0ZZS1ZYOQ?oc=5" target="_blank">US House speaker urges lawmakers to avoid town hall meetings</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMinAFBVV95cUxPTHFlREZIaGRnX3ZIUnFBZFlLYzRSNW5EYjZULVZ6bWZsS3IwX2J5M2c4cDRRc1dOcGwtblg3ZmJlYkQ3RkJZeE9fbWlQUU8yOXB6SVpXbkQ3RUpBMlNCYk5FT1FhSWJqV0M1UHVxTVkyNnNXR05ENWxILVJucFJYeTdLQTdSc3lPVEp2dVdUUWNwd2dLNlZHX2tSVVc?oc=5" target="_blank">No more in-person town halls, NRCC chief tells House Republicans</a>&nbsp;&nbsp;<font color="#6f6f6f">POLITICO</font></li></ol>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en', 'value': '<ol><li><a href="https://news.google.com/rss/articles/CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UXRMX0FxY01rZDFRRHpvbEkzVFd1RGhKbUtWZjcteVVLMENnU2ZhU292TFdEVWFSaTViVXN2LTBMUVlMVHNhazA5ZF9vM0FBS2E4YmdseTdqcXdoaWxZdHR0bl9wWXRRQWRNdnhOajdFX29LV1NuRFRRSk5TUHo0?oc=5" target="_blank">Speaker Johnson tells GOP lawmakers to skip town halls after an onslaught of protests</a>&nbsp;&nbsp;<font color="#6f6f6f">The Associated Press</font></li><li><a href="https://news.google.com/rss/articles/CBMihwFBVV95cUxPYmgwYVhLdzhKUnE0d0U5ZFA5bDBFQW5kaFBxbHloNXZjTEE2UTNJN2plUUtpWXVQRUR0WURYdUd5NU82NldYSUVBTmx1elltT29hRjZDWVI0b0k4MWJ6azZxQmppdVVlckFLUmhxR1JCLWZ5MkFQOFNsV3psNEEtQVBLTjhkNUk?oc=5" target="_blank">After explosive town halls, Republicans rethink how to reach voters</a>&nbsp;&nbsp;<font color="#6f6f6f">The Washington Post</font></li><li><a href="https://news.google.com/rss/articles/CBMipAFBVV95cUxQNlJCWlA0bXBZZExCUW84N3MtQllTZXgwZFZuOG52SUdCRGVRMUF6aXZVNUVWQzhDdHhuUTFUMjNJZFhmS19wSmV6RlVRakJRbUdXeG0zTGRDWThoeThFaVBTcV9HNVktWHh0bVdNVkpWSVFaSm5fTHNhT1QzU1VVS28tUm9XaHgycEZYOFpEN0dpb290U053S044ZEtXY0ZZS1ZYOQ?oc=5" target="_blank">US House speaker urges lawmakers to avoid town hall meetings</a>&nbsp;&nbsp;<font color="#6f6f6f">Reuters</font></li><li><a href="https://news.google.com/rss/articles/CBMinAFBVV95cUxPTHFlREZIaGRnX3ZIUnFBZFlLYzRSNW5EYjZULVZ6bWZsS3IwX2J5M2c4cDRRc1dOcGwtblg3ZmJlYkQ3RkJZeE9fbWlQUU8yOXB6SVpXbkQ3RUpBMlNCYk5FT1FhSWJqV0M1UHVxTVkyNnNXR05ENWxILVJucFJYeTdLQTdSc3lPVEp2dVdUUWNwd2dLNlZHX2tSVVc?oc=5" target="_blank">No more in-person town halls, NRCC chief tells House Republicans</a>&nbsp;&nbsp;<font color="#6f6f6f">POLITICO</font></li></ol>'}, 'source': {'href': 'https://apnews.com', 'title': 'The Associated Press'}}

,title,title_detail,links,link,id,guidislink,published,published_parsed,summary,summary_detail,source
0,Watch: Congressman Al Green ejected from chamb...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiV0FVX...,CBMiV0FVX3lxTE5OTUVKN0VsZkF5bVJCVnN3bjlxRjlvX3...,False,"Wed, 05 Mar 2025 02:44:52 GMT","(2025, 3, 5, 2, 44, 52, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.bbc.com', 'title': 'BBC...."
1,"Trump’s Latest Tariffs on Canada, Mexico and C...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMigAFBV...,CBMigAFBVV95cUxNY2pOenhzX25QQlZNUEZSc0tkVXVITW...,False,"Wed, 05 Mar 2025 01:30:23 GMT","(2025, 3, 5, 1, 30, 23, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
2,Speaker Johnson tells GOP lawmakers to skip to...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxPSFg1ajlDOW90VmE1QzJRcXBidDM2UX...,False,"Tue, 04 Mar 2025 17:35:00 GMT","(2025, 3, 4, 17, 35, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://apnews.com', 'title': 'The A..."
3,Zelenskyy suggests Ukraine didn't receive dire...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMixwFBV...,CBMixwFBVV95cUxOdk1KQ1FWM0FTemtNeHV4TkVzejQ4X1...,False,"Tue, 04 Mar 2025 21:00:11 GMT","(2025, 3, 4, 21, 0, 11, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.pbs.org', 'title': 'PBS ..."
4,Texas besieged by multiple fires as deadly sto...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMimwFBV...,CBMimwFBVV95cUxPRVBxY29yS2JlTE1pSEt2Q2RmU05TeX...,False,"Wed, 05 Mar 2025 01:38:00 GMT","(2025, 3, 5, 1, 38, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.cnn.com', 'title': 'CNN'}"
5,Trump admin wants to sell off DOJ headquarters...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMisgFBV...,CBMisgFBVV95cUxOSFhRQTYweUlsQWZhOXcxNXBDd3Z3QV...,False,"Tue, 04 Mar 2025 21:26:00 GMT","(2025, 3, 4, 21, 26, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.independent.co.uk', 'tit..."
6,Takeaways from Trump’s address to Congress - CNN,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiiwFBV...,CBMiiwFBVV95cUxOamcyNS00amNTYms0SVhXR2lfMFZ6Mj...,False,"Wed, 05 Mar 2025 03:26:00 GMT","(2025, 3, 5, 3, 26, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.cnn.com', 'title': 'CNN'}"
7,LA City Council votes not to reinstate fire ch...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMimAFBV...,CBMimAFBVV95cUxNNS0tV1RXdkEta19IWURaMHNLN1d6NE...,False,"Tue, 04 Mar 2025 21:39:56 GMT","(2025, 3, 4, 21, 39, 56, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://abcnews.go.com', 'title': 'A..."
8,"Lincoln Díaz-Balart, a ‘Free Cuba’ Republican ...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiggFBV...,CBMiggFBVV95cUxOMFlESGJYelVGVjQ4MkhoUzJCR0g3QU...,False,"Tue, 04 Mar 2025 22:53:33 GMT","(2025, 3, 4, 22, 53, 33, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
9,Myah Selland speaks out against anti-trans leg...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMipAFBV...,CBMipAFBVV95cUxNOVFQWTh0d3c3V3JZRFpaS2cxcjhsUk...,False,"Tue, 04 Mar 2025 21:26:18 GMT","(2025, 3, 4, 21, 26, 18, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.keloland.com', 'title': ..."
10,Arab leaders adopt Gaza reconstruction plan in...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMifkFVX...,CBMifkFVX3lxTE1JTXMzS2dZZGpaRXpVdzRzNUpZNlJUNj...,False,"Wed, 05 Mar 2025 03:11:53 GMT","(2025, 3, 5, 3, 11, 53, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.washingtonpost.com', 'ti..."
11,JD Vance sparks British fury as he mocks Ukrai...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMipwFBV...,CBMipwFBVV95cUxQbngzTWtWS09PREJaWGtfZWxvWnpDX0...,False,"Tue, 04 Mar 2025 11:58:00 GMT","(2025, 3, 4, 11, 58, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.politico.eu', 'title': '..."
12,America vs. The World: Trump Shows How Far He ...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMie0FVX...,CBMie0FVX3lxTFBucVRKZ19RWXhXdnY5QXJUZjRzaURmam...,False,"Tue, 04 Mar 2025 18:30:20 GMT","(2025, 3, 4, 18, 30, 20, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
13,Pope Francis in stable condition after episode...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxOVF9xZHRtZExuaXBTcTU3SFdIV1ZQeU...,False,"Tue, 04 Mar 2025 18:57:00 GMT","(2025, 3, 4, 18, 57, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://edition.cnn.com', 'title': '..."
14,Best Buy and Target CEOs say prices are about ...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMifkFVX...,CBMifkFVX3lxTE1zaEczVWROXzFyRUhOMGQwaHUzcUY4dk...,False,"Tue, 04 Mar 2025 22:43:33 GMT","(2025, 3, 4, 22, 43, 33, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.theverge.com', 'title': ..."
15,China sets annual economic growth target of 5%...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMicEFVX...,CBMicEFVX3lxTE1yYThwVlBpUTY2Q09wLTNjOGlIblpXaU...,False,"Wed, 05 Mar 2025 00:27:02 GMT","(2025, 3, 5, 0, 27, 2, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.ft.com', 'title': 'Finan..."
16,"Dow tumbles again, loses more than 1,300 point...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMid0FVX...,CBMid0FVX3lxTE1BRGJEOGFsdTRSTzY0c3Z0N3JjcjEtZD...,False,"Tue, 04 Mar 2025 21:33:00 GMT","(2025, 3, 4, 21, 33, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.cnbc.com', 'title': 'CNBC'}"
17,Goldman Sachs set to ax under-performing VPs i...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMinwFBV...,CBMinwFBVV95cUxOX3VXaGVLTmVfRDJhLVRETlJJdlFCUD...,False,"Tue, 04 Mar 2025 21:44:00 GMT","(2025, 3, 4, 21, 44, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://nypost.com', 'title': 'New Y..."
18,Looking for a cheaper iPad with Apple Intellig...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMid0FVX...,CBMid0FVX3lxTFA2VWR4TE55TTRZcUV6U1Njc002clVPdk...,False,"Tue, 04 Mar 2025 20:47:00 GMT","(2025, 3, 4, 20, 47, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://9to5mac.com', 'title': '9to5..."
19,Google’s Latest Pixel Feature Drop Will Let Pi...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMisgFBV...,CBMisgFBVV95cUxPZGFZY3QzWmtueFVaT2hXMENobnl6ST...,False,"Tue, 04 Mar 2025 17:01:05 GMT","(2025, 3, 4, 17, 1, 5, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://gizmodo.com', 'title': 'Gizm..."
20,Nvidia’s GeForce RTX 5070 Founders Edition car...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxPMWRIUWhOSGR0a3pERlo2b1ZjU01NYW...,False,"Tue, 04 Mar 2025 22:51:17 GMT","(2025, 3, 4, 22, 51, 17, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.theverge.com', 'title': ..."
21,Eerily realistic AI voice demo sparks amazemen...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiqAFBV...,CBMiqAFBVV95cUxNR2J0NXAtSGNXZ2Rlc1hBVFFPbU1PeD...,False,"Tue, 04 Mar 2025 23:35:01 GMT","(2025, 3, 4, 23, 35, 1, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://arstechnica.com', 'title': '..."
22,A Rare Encounter With Dolly Parton’s Elusive H...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiowFBV...,CBMiowFBVV95cUxQZHI5VjNNVWhxSXgxejhZWGxLdVFyOU...,False,"Tue, 04 Mar 2025 23:17:00 GMT","(2025, 3, 4, 23, 17, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://variety.com', 'title': 'Vari..."
23,‘Daredevil: Born Again’ TV Review: Disney+’s L...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMid0FVX...,CBMid0FVX3lxTE1YenhzeFA0NUhITWotai1vOXJnZVJ3en...,False,"Wed, 05 Mar 2025 02:01:00 GMT","(2025, 3, 5, 2, 1, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://deadline.com', 'title': 'Dea..."
24,Americans Apply for U.K. Citizenship in Record...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilwFBV...,CBMilwFBVV95cUxPTEN5LVc2VUVYRnNBaDRyaWoyN0ZlMG...,False,"Wed, 05 Mar 2025 02:15:00 GMT","(2025, 3, 5, 2, 15, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.thedailybeast.com', 'tit..."
25,Gene Hackman’s dog was misidentified as other ...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilgFBV...,CBMilgFBVV95cUxPM1B4N3R0YU9GaHZKcWxQSktIbFZuMU...,False,"Wed, 05 Mar 2025 01:31:00 GMT","(2025, 3, 5, 1, 31, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://apnews.com', 'title': 'The A..."
26,Mavericks star Kyrie Irving has a torn ACL and...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMimgFBV...,CBMimgFBVV95cUxQTS12SS1rak5uNzEycmg2Tk40dy1VcD...,False,"Wed, 05 Mar 2025 02:48:00 GMT","(2025, 3, 5, 2, 48, 0, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://apnews.com', 'title': 'The A..."
27,Jets Release WR Davante Adams - newyorkjets.com,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMifkFVX...,CBMifkFVX3lxTFBlQ3gtUktMVERIbzV6RTVRX3g0X2NtV1...,False,"Tue, 04 Mar 2025 21:40:40 GMT","(2025, 3, 4, 21, 40, 40, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.newyorkjets.com', 'title..."
28,New rumors of Shedeur Sanders’ ‘unprofessional...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiqgFBV...,CBMiqgFBVV95cUxQQzBadUl3WHJsSzhKN3c4MGRJUmpxRH...,False,"Tue, 04 Mar 2025 21:26:00 GMT","(2025, 3, 4, 21, 26, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://nypost.com', 'title': 'New Y..."
29,Wide Receivers in Free Agency | Who’s Out Ther...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMilAFBV...,CBMilAFBVV95cUxNTzJzem9iSlhCQ1VaWXVFam03SzVveF...,False,"Tue, 04 Mar 2025 18:12:46 GMT","(2025, 3, 4, 18, 12, 46, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.baltimoreravens.com', 't..."
30,“Wooly mice” a test run for mammoth gene editi...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMikAFBV...,CBMikAFBVV95cUxOVnk4R2w3ZUEzd01nbER6dUw3Sk5LcW...,False,"Tue, 04 Mar 2025 23:03:45 GMT","(2025, 3, 4, 23, 3, 45, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://arstechnica.com', 'title': '..."
31,SpaceX sets date for next Starship launch. Her...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiiAFBV...,CBMiiAFBVV95cUxPVHQtN3U2RGlkWHlmcV9UZk1kckwxRH...,False,"Wed, 05 Mar 2025 02:43:23 GMT","(2025, 3, 5, 2, 43, 23, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.chron.com', 'title': 'Ch..."
32,NASA's two stuck astronauts are finally closin...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMisAFBV...,CBMisAFBVV95cUxOemZQOVZTaG9KX3ZNTE44V210MXpfNn...,False,"Tue, 04 Mar 2025 18:45:55 GMT","(2025, 3, 4, 18, 45, 55, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://abcnews.go.com', 'title': 'A..."
33,‘Moon Dust on Our Boots’: Texas Company’s Blue...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMikwFBV...,CBMikwFBVV95cUxPX1N1ektQbkd6enFfamdmQmpxLW9naE...,False,"Tue, 04 Mar 2025 04:10:00 GMT","(2025, 3, 4, 4, 10, 0, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
34,"As Measles Spreads, Kennedy Embraces Remedies ...","{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMigwFBV...,CBMigwFBVV95cUxPU3BKVnNiQllwLW9qb0JGTEh6dVVYRX...,False,"Tue, 04 Mar 2025 22:47:33 GMT","(2025, 3, 4, 22, 47, 33, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.nytimes.com', 'title': '..."
35,Dysentery is on the rise in Oregon. Here’s wha...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMijAFBV...,CBMijAFBVV95cUxPVGE5bUlPMjhuUUxJNVd3Z204WUF4bn...,False,"Wed, 05 Mar 2025 02:52:46 GMT","(2025, 3, 5, 2, 52, 46, 2, 64, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.washingtonpost.com', 'ti..."
36,Why Sleep Gets Harder With Age - Newsmax,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMikwFBV...,CBMikwFBVV95cUxQa3J1OTl4cXZoQUNiSVFPYjAyTDBLR2...,False,"Tue, 04 Mar 2025 19:18:15 GMT","(2025, 3, 4, 19, 18, 15, 1, 63, 0)","<a href=""https://news.google.com/rss/articles/...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.newsmax.com', 'title': '..."
37,Presidential Message on Colorectal Cancer Awar...,"{'type': 'text/plain', 'language': None, 'base...","[{'rel': 'alternate', 'type': 'text/html', 'hr...",https://news.google.com/rss/articles/CBMiuwFBV...,CBMiuwFBVV95cUxQak5icHd5cV9Ia0FmSFVsQ3h3M1lKT0...,False,"Tue, 04 Mar 2025 14:43:19 GMT","(2025, 3, 4, 14, 43, 19, 1, 63, 0)","<ol><li><a href=""https://news.google.com/rss/a...","{'type': 'text/html', 'language': None, 'base'...","{'href': 'https://www.whitehouse.gov', 'title'..."

In [41]:
import streamlit as st
import altair as alt
import pandas as pd
from vega_datasets import data


@st.cache_data
def get_data():
    source = data.stocks()
    source = source[source.date.gt("2004-01-01")]
    return source


stock_data = get_data()

hover = alt.selection_single(
    fields=["date"],
    nearest=True,
    on="mouseover",
    empty="none",
)

lines = (
    alt.Chart(stock_data, title="Evolution of stock prices")
    .mark_line()
    .encode(
        x="date",
        y="price",
        color="symbol",
    )
)

points = lines.transform_filter(hover).mark_circle(size=65)

tooltips = (
    alt.Chart(stock_data)
    .mark_rule()
    .encode(
        x="yearmonthdate(date)",
        y="price",
        opacity=alt.condition(hover, alt.value(0.3), alt.value(0)),
        tooltip=[
            alt.Tooltip("date", title="Date"),
            alt.Tooltip("price", title="Price (USD)"),
        ],
    )
    .add_selection(hover)
)

data_layer = lines + points + tooltips

ANNOTATIONS = [
    ("Sep 01, 2007", 450, "🙂", "Something's going well for GOOG & AAPL."),
    ("Nov 01, 2008", 220, "🙂", "The market is recovering."),
    ("Dec 01, 2007", 750, "😱", "Something's going wrong for GOOG & AAPL."),
    ("Dec 01, 2009", 680, "😱", "A hiccup for GOOG."),
]
annotations_df = pd.DataFrame(
    ANNOTATIONS, columns=["date", "price", "marker", "description"]
)
annotations_df.date = pd.to_datetime(annotations_df.date)

annotation_layer = (
    alt.Chart(annotations_df)
    .mark_text(size=20, dx=-10, dy=0, align="left")
    .encode(x="date:T", y=alt.Y("price:Q"), text="marker", tooltip="description")
)

combined_chart = data_layer + annotation_layer
st.altair_chart(combined_chart, use_container_width=True)

2025-03-05 02:48:24.405 No runtime found, using MemoryCacheStorageManager
2025-03-05 02:48:24.408 No runtime found, using MemoryCacheStorageManager
2025-03-05 02:48:24.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-05 02:48:24.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-05 02:48:24.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-05 02:48:24.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-05 02:48:24.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
<ipython-input-41-8e08531a0bbe>:16: AltairDeprecationWarning:
Deprecated since `altair=5.0.0`. Use selection_point instead.
  hover = alt.selection_single(
<ipython-input-41-8e08531a0bbe>:47: AltairDeprecationWarning:
Deprecated since `altair=5.0.0`. Use add_params instead.
  .add_selection(hover)
2025-03-05 02:48:24.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-05 02:48:24.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [40]:
# |exporti

st.title("Example")

# Example